name: newbuddy
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  zego_uikit_prebuilt_call: ^4.19.0
  permission_handler: ^12.0.1
  grpc: ^4.3.1
  protobuf: ^5.1.0
  logging: ^1.2.0
  record: 6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  protoc_plugin: ^24.0.0

flutter:
  uses-material-design: true
