name: newbuddy
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  zego_uikit: ^2.28.34
  zego_uikit_prebuilt_call: ^4.21.1
  zego_uikit_signaling_plugin: ^2.8.19
  permission_handler: ^12.0.1
  cupertino_icons: ^1.0.2
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
